import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Users, 
  CreditCard, 
  DollarSign, 
  Download,
  Calendar,
  Activity,
  RefreshCw
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import AdminLayout from '../../components/admin/AdminLayout';
import jsPDF from 'jspdf';
import { dashboardService, DashboardStats, RecentActivity } from '../../services/dashboardService';

const AdminDashboard: React.FC = () => {
  const { adminUser } = useApp();
  const navigate = useNavigate();
  const [stats, setStats] = useState<DashboardStats>({
    totalUsers: 0,
    totalPayments: 0,
    totalRevenue: 0,
    totalTemplates: 0,
    premiumUsers: 0,
    activeUsers: 0
  });
  const [recentActivity, setRecentActivity] = useState<RecentActivity[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);

  // Load dashboard data
  const loadDashboardData = async () => {
    try {
      setLoading(true);
      setError(null);
      
      const [dashboardStats, activityData] = await Promise.all([
        dashboardService.getDashboardStats(),
        dashboardService.getRecentActivity()
      ]);
      
      setStats(dashboardStats);
      setRecentActivity(activityData);
      setLastUpdated(new Date());
    } catch (err) {
      console.error('Error loading dashboard data:', err);
      setError('Failed to load dashboard data. Please try refreshing.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!adminUser) {
      navigate('/admin/login');
      return;
    }
    
    loadDashboardData();
  }, [adminUser, navigate]);

  const downloadReport = () => {
    const pdf = new jsPDF();
    const currentDate = new Date().toLocaleDateString();
    
    // Header
    pdf.setFontSize(20);
    pdf.text('CardCraft Admin Dashboard Report', 20, 30);
    
    pdf.setFontSize(12);
    pdf.text(`Generated on: ${currentDate}`, 20, 45);
    pdf.text(`Generated by: ${adminUser?.username}`, 20, 55);
    pdf.text(`Data last updated: ${lastUpdated?.toLocaleString() || 'N/A'}`, 20, 65);
    
    // Statistics
    pdf.setFontSize(16);
    pdf.text('Key Statistics', 20, 85);
    
    pdf.setFontSize(12);
    pdf.text(`Total Users: ${stats.totalUsers}`, 20, 100);
    pdf.text(`Active Users: ${stats.activeUsers}`, 20, 110);
    pdf.text(`Premium Users: ${stats.premiumUsers}`, 20, 120);
    pdf.text(`Total Payments: ${stats.totalPayments}`, 20, 130);
    pdf.text(`Total Revenue: $${stats.totalRevenue.toFixed(2)}`, 20, 140);
    pdf.text(`Total Templates: ${stats.totalTemplates}`, 20, 150);
    
    // Recent Activity
    pdf.setFontSize(16);
    pdf.text('Recent Activity', 20, 190);
    
    pdf.setFontSize(10);
    let yPosition = 205;
    recentActivity.forEach((activity, index) => {
      if (yPosition > 270) {
        pdf.addPage();
        yPosition = 20;
      }
      pdf.text(`${index + 1}. ${activity.message} (${activity.time})`, 20, yPosition);
      yPosition += 10;
    });
    
    // Footer
    pdf.setFontSize(8);
    pdf.text('This report is confidential and for internal use only.', 20, 280);
    
    pdf.save(`cardcraft-dashboard-report-${currentDate.replace(/\//g, '-')}.pdf`);
  };

  if (!adminUser) {
    return null;
  }

  if (loading) {
    return (
      <AdminLayout>
        <div className="flex items-center justify-center h-64">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
            <p className="mt-4 text-gray-600">Loading dashboard data...</p>
          </div>
        </div>
      </AdminLayout>
    );
  }

  return (
    <AdminLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Dashboard</h1>
            <p className="text-gray-600">Welcome back, {adminUser.username}</p>
            {lastUpdated && (
              <p className="text-sm text-gray-500">Last updated: {lastUpdated.toLocaleString()}</p>
            )}
            {error && (
              <div className="mt-2 p-3 bg-red-100 border border-red-400 text-red-700 rounded">
                {error}
              </div>
            )}
          </div>
          <div className="flex space-x-2">
            <button
              onClick={loadDashboardData}
              disabled={loading}
              className="flex items-center bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700 transition-colors disabled:opacity-50"
            >
              <RefreshCw className={`h-4 w-4 mr-2 ${loading ? 'animate-spin' : ''}`} />
              Refresh
            </button>
            <button
              onClick={downloadReport}
              className="flex items-center bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
            >
              <Download className="h-4 w-4 mr-2" />
              Download Report
            </button>
          </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center">
              <Users className="h-8 w-8 text-blue-600" />
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-600">Total Users</p>
                <p className="text-2xl font-bold text-gray-900">{stats.totalUsers.toLocaleString()}</p>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center">
              <DollarSign className="h-8 w-8 text-green-600" />
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-600">Total Revenue</p>
                <p className="text-2xl font-bold text-gray-900">${stats.totalRevenue.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</p>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center">
              <CreditCard className="h-8 w-8 text-purple-600" />
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-600">Total Payments</p>
                <p className="text-2xl font-bold text-gray-900">{stats.totalPayments.toLocaleString()}</p>
              </div>
            </div>
          </div>

        </div>

        {/* Additional Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Active Users</p>
                <p className="text-3xl font-bold text-gray-900">{stats.activeUsers.toLocaleString()}</p>
              </div>
              <Activity className="h-8 w-8 text-green-600" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Premium Users</p>
                <p className="text-3xl font-bold text-gray-900">{stats.premiumUsers.toLocaleString()}</p>
              </div>
              <Users className="h-8 w-8 text-purple-600" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total Templates</p>
                <p className="text-3xl font-bold text-gray-900">{stats.totalTemplates.toLocaleString()}</p>
              </div>
              <Calendar className="h-8 w-8 text-blue-600" />
            </div>
          </div>
        </div>

        {/* Recent Activity */}
        <div className="bg-white rounded-lg shadow">
          <div className="px-6 py-4 border-b border-gray-200">
            <h2 className="text-lg font-semibold text-gray-900">Recent Activity</h2>
          </div>
          <div className="p-6">
            <div className="space-y-4">
              {recentActivity.length > 0 ? (
                recentActivity.map((activity) => (
                  <div key={activity.id} className="flex items-start space-x-3">
                    <div className={`flex-shrink-0 w-2 h-2 rounded-full mt-2 ${
                      activity.type === 'user' ? 'bg-blue-500' :
                      activity.type === 'payment' ? 'bg-green-500' :
                      'bg-purple-500'
                    }`} />
                    <div className="flex-1">
                      <p className="text-sm text-gray-900">{activity.message}</p>
                      <p className="text-xs text-gray-500">{activity.time}</p>
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-center py-8">
                  <p className="text-gray-500">No recent activity found</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </AdminLayout>
  );
};

export default AdminDashboard;